import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-0 text-[0.98rem] leading-7 text-foreground/90",
  quote: "border-l-4 border-primary pl-4 italic text-muted-foreground my-7",
  heading: {
    h1: "text-4xl font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
    h2: "text-3xl font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
    h3: "text-2xl font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
    h4: "text-xl font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
    h5: "text-lg font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
    h6: "text-base font-semibold mt-7 mb-0 leading-7 font-display tracking-tight",
  },
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal list-outside ml-6 my-0",
    ul: "list-disc list-outside ml-6 my-0",
    listitem: "mb-0",
    listitemChecked:
      'relative pl-7 list-none before:content-["✓"] before:absolute before:left-0 before:text-primary before:font-bold',
    listitemUnchecked:
      'relative pl-7 list-none before:content-["○"] before:absolute before:left-0 before:text-muted-foreground',
  },
  link: "text-primary underline hover:text-primary/80 cursor-pointer",
  text: {
    bold: "font-bold",
    code: "bg-muted px-1.5 py-0.5 rounded text-sm font-mono",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "align-sub text-xs",
    superscript: "align-super text-xs",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
  },
  code: "block bg-muted text-foreground font-mono text-sm p-4 rounded my-7 overflow-x-auto",
  codeHighlight: {
    atrule: "text-purple-600 dark:text-purple-400",
    attr: "text-cyan-600 dark:text-cyan-400",
    boolean: "text-orange-600 dark:text-orange-400",
    builtin: "text-pink-600 dark:text-pink-400",
    cdata: "text-gray-500 dark:text-gray-400",
    char: "text-green-600 dark:text-green-400",
    class: "text-blue-600 dark:text-blue-400",
    "class-name": "text-blue-600 dark:text-blue-400",
    comment: "text-gray-500 dark:text-gray-400 italic",
    constant: "text-orange-600 dark:text-orange-400",
    deleted: "text-red-600 dark:text-red-400",
    doctype: "text-gray-500 dark:text-gray-400",
    entity: "text-yellow-600 dark:text-yellow-400",
    function: "text-blue-600 dark:text-blue-400",
    important: "text-red-600 dark:text-red-400 font-bold",
    inserted: "text-green-600 dark:text-green-400",
    keyword: "text-purple-600 dark:text-purple-400 font-semibold",
    namespace: "text-pink-600 dark:text-pink-400",
    number: "text-orange-600 dark:text-orange-400",
    operator: "text-yellow-600 dark:text-yellow-400",
    prolog: "text-gray-500 dark:text-gray-400",
    property: "text-cyan-600 dark:text-cyan-400",
    punctuation: "text-gray-600 dark:text-gray-300",
    regex: "text-red-600 dark:text-red-400",
    selector: "text-green-600 dark:text-green-400",
    string: "text-green-600 dark:text-green-400",
    symbol: "text-orange-600 dark:text-orange-400",
    tag: "text-red-600 dark:text-red-400",
    url: "text-blue-600 dark:text-blue-400 underline",
    variable: "text-pink-600 dark:text-pink-400",
  },
};
